-- SQLite doesn't support DROP COLUMN directly in older versions
-- SQLite 3.35.0+ supports ALTER TABLE DROP COLUMN
-- For safety, we'll leave this as a no-op
-- In production, you may need a full table recreation for older SQLite versions
